In [1]:
import numpy as np

# converting a list to array

In [2]:
lst=[1,2,3,4]
print(type(lst))

arr=np.array(lst)
print(type(arr))
print(arr)
print(arr.ndim)

arr=np.array(lst,ndmin=2)
print(arr)
print(arr.ndim)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]
1
[[1 2 3 4]]
2


# 2. Arrange funciton

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# 3. multidimensional Array

In [5]:
arr=np.array([[1,2,3,1],[2,4,5,6],[3,7,8,9]])
arr

array([[1, 2, 3, 1],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

# 4. Size Function

In [6]:
arr.size

12

In [7]:
print("total     :",arr.size)
print("total Row :",np.size(arr,0))
print("total Col :",np.size(arr,1))

total     : 12
total Row : 3
total Col : 4


# 5. Shape Function

In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

arr.shape

(2, 4)

# 6. Dtype Function

In [9]:
arr=np.array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
arr1=np.array([1,5.2,4.5,5])
print(arr1.dtype)
arr.dtype


float64


dtype('int32')

# 7. Ndim Function

In [10]:
arr1=np.array([[1,2,3],[4.5,4,6]])

arr1.ndim

2

# 8. Zeros Function

In [11]:
a=np.zeros(shape=(5,5))
print(a.dtype)
a

float64


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a=np.zeros(shape=(3,5),dtype=int)
a.dtype

dtype('int32')

# 9. Eyw Function

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 10. Empty Function

In [15]:
np.empty(shape = (5,6))

array([[1.47678212e-311, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 2.22526399e-307, 1.16097020e-028],
       [8.26330279e-072, 2.54818291e-028, 5.39178807e-062,
        1.04917183e-153, 5.23081515e-143, 5.40358723e-038],
       [2.19507801e-056, 4.66822222e-062, 1.36967059e-071,
        1.70098498e+256, 5.49109388e-143, 1.06396443e+224],
       [3.96041428e+246, 1.16318408e-028, 1.25865857e-047,
        2.10816752e-052, 5.98251315e+174, 2.65008006e-032],
       [1.01848862e+248, 1.16096643e-028, 9.80058441e+252,
        7.50189709e+247, 1.14484251e+243, 2.59903827e-144]])

 # 11. Random Function

## a) np.random.rand

In [16]:
np.random.rand(3,4)

array([[0.95618625, 0.42300929, 0.73199959, 0.66042444],
       [0.20455316, 0.0548072 , 0.44340915, 0.0402402 ],
       [0.73911504, 0.5566176 , 0.00544098, 0.93587267]])

## b) np.random.randint

In [17]:
np.random.randint(1,10,5)

array([7, 9, 1, 3, 9])

In [18]:
np.random.randint(low=1,high=15,size=12)

array([ 5,  1,  1,  4,  4, 10,  9,  8, 11,  5, 10,  3])

## c) np.random.randn

In [19]:
np.random.randn(100)

array([ 0.47190823, -0.5393366 ,  1.66435383,  0.73400975, -1.21732205,
        1.59329462, -0.26265533,  0.45413346, -0.6766069 ,  1.33318452,
       -1.22153826,  1.88064243,  0.99573696, -0.66036898,  0.59618825,
        0.05164568, -1.39020983,  0.83976047, -1.4535565 ,  0.78766957,
       -0.50989623,  1.08198947,  0.42052723,  1.14163273,  0.59937775,
       -1.68527212,  0.20480651,  0.02283811, -0.48116063,  0.89951337,
        1.17846241,  0.30498023, -1.97361642,  0.33456672, -1.06559258,
       -0.34328456, -0.60292548, -1.60930463,  0.31107588,  0.26607768,
        0.00988174, -1.54902288,  0.36694575, -0.51941791, -0.14084022,
       -0.18526511,  0.79403484,  0.44699687,  1.29151646, -0.45377317,
       -1.37099398,  0.50165523,  0.00278413, -0.87732857,  0.77932066,
        0.29226945,  0.23122365, -1.67886675, -0.87947197,  0.24786943,
       -1.43217519,  1.23712441,  0.36361274, -0.30934281,  1.51563764,
       -1.54693348,  0.51479882, -0.57580353,  0.46766861,  0.65

# 12. Reshape Function 

In [20]:
arr=np.random.randint(1,15,(3,4))
print(arr)
print(arr.shape)
arr=arr.reshape(4,3)
print(arr.shape)
print(arr)
print(arr.reshape(6,2))

[[ 2  5  4  7]
 [ 4 14  6  7]
 [ 4 11  2  8]]
(3, 4)
(4, 3)
[[ 2  5  4]
 [ 7  4 14]
 [ 6  7  4]
 [11  2  8]]
[[ 2  5]
 [ 4  7]
 [ 4 14]
 [ 6  7]
 [ 4 11]
 [ 2  8]]


# 13. Linspace Function

In [21]:
np.linspace(0,10,5)
# np.random.randint(0,10,5)
# np.arange(0,10,2)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 14. Flatten Function

In [22]:
arr =np.arange(1,13)
arr=arr.reshape(3,4)
print(arr.shape)
print(arr)
arr=arr.flatten()
print(arr.shape)
print(arr)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 15. Logspace Function

In [23]:
np.logspace(2,4,5)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

# 16. copy arry

In [24]:
arr1=np.random.randint(1,15,10)
arr2=arr1
print(arr1,id(arr1))
print(arr2,id(arr2))


print("-"*50)
arr1=np.random.randint(1,100,(10))
arr2=np.copy(arr1)
print(arr1,id(arr1))
print(arr2,id(arr2))

[ 3  1  6  6  9  7 10  6 13  6] 2989241734256
[ 3  1  6  6  9  7 10  6 13  6] 2989241734256
--------------------------------------------------
[30 94 54  1 67 12 16 29  8 76] 2989241733968
[30 94 54  1 67 12 16 29  8 76] 2989241450288


# 17. arr.min() arr.max() arr.sum() function

In [25]:
arr=np.random.randint(1,45,(3,4))
print ("-"*30,"\n",arr,"-"*30)
print("minimum value of arr =>",arr.min())
print("maximum value of arr =>",arr.max())
print("sum of arr elemant =>",arr.sum())


------------------------------ 
 [[12 43 22 36]
 [39 18 35 31]
 [21 28  5 11]] ------------------------------
minimum value of arr => 5
maximum value of arr => 43
sum of arr elemant => 301


## column=0
## row=1

In [26]:
arr=np.random.randint(1,100,(3,5))
print(arr)
print("\n","-"*25,"Column","-"*25)
print("minimum value of arr in column =>",arr.min(axis=0))
print("maximum value of arr in column =>",arr.max(axis=0))
print("sum of arr elemant in column =>",arr.sum(axis=0))
print("\n","-"*25,"Row","-"*25)
print("minimum value of arr in column =>",arr.min(axis=1))
print("maximum value of arr in column =>",arr.max(axis=1))
print("sum of arr elemant in column =>",arr.sum(axis=1))


[[93 31 50 58 71]
 [21 84 86 49 18]
 [52 51 11 13 79]]

 ------------------------- Column -------------------------
minimum value of arr in column => [21 31 11 13 18]
maximum value of arr in column => [93 84 86 58 79]
sum of arr elemant in column => [166 166 147 120 168]

 ------------------------- Row -------------------------
minimum value of arr in column => [31 18 11]
maximum value of arr in column => [93 86 79]
sum of arr elemant in column => [303 258 206]


# 18. seed function

In [27]:
np.random.seed(3)#using this function we can 
arr=np.random.randint(1,15,(3,4))
arr

array([[11,  9, 10,  4],
       [ 9,  9,  1,  6],
       [14,  4, 11, 12]])

In [28]:
arr=np.random.randint(1,15,(3,4))
arr

array([[10, 10, 11,  6],
       [ 8,  7,  1,  5],
       [13, 14,  8,  9]])

# 19. np.sort(arr) 

In [43]:
### arr=np.arange(1,16)
arr=arr.reshape(3,5)
arr
np.random.seed(3)
arr=np.random.randint(1,45,(3,5))
print(arr)
print("-"*50)
print(np.sort(arr))
print("-"*50)
print(np.sort(arr,axis=0))

print('-'*50)
arr=np.reshape(np.sort(arr.flatten()),(3,5))
arr

[[43 25  4  9  1]
 [22 20 11 44 42]
 [11 22 39 33 21]]
--------------------------------------------------
[[ 1  4  9 25 43]
 [11 20 22 42 44]
 [11 21 22 33 39]]
--------------------------------------------------
[[11 20  4  9  1]
 [22 22 11 33 21]
 [43 25 39 44 42]]
--------------------------------------------------


array([[ 1,  4,  9, 11, 11],
       [20, 21, 22, 22, 25],
       [33, 39, 42, 43, 44]])

# 20.  Mathematical Oprations

# Addition (+)

In [44]:
np.random.seed(3)
arr=np.random.randint(1,78,(3,5))
print(arr)
print("-"*15)
print(arr+1)


[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 21 45 40]]
---------------
[[26  5 58 74  2]
 [23 21 76 43 12]
 [23 40 22 46 41]]


# Substraction

In [45]:
print(arr)
print('-'*15)
print(arr-5)

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 21 45 40]]
---------------
[[20 -1 52 68 -4]
 [17 15 70 37  6]
 [17 34 16 40 35]]


# Multiplication

In [46]:
print(arr)
print('-'*15)
print(arr*2)

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 21 45 40]]
---------------
[[ 50   8 114 146   2]
 [ 44  40 150  84  22]
 [ 44  78  42  90  80]]


# Division

In [48]:
print(arr)
print('-'*15)
print(arr/2)

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 21 45 40]]
---------------
[[12.5  2.  28.5 36.5  0.5]
 [11.  10.  37.5 21.   5.5]
 [11.  19.5 10.5 22.5 20. ]]


# Matrix Multiplication

In [106]:
np.random.seed(3)
arr1=np.random.randint(1,150,(3,5))
arr2=np.random.randint(1,150,(5,3))
print(arr1.dot(arr2))
print('-'*15)
print(arr2.dot(arr1))

arr2@arr1

[[27881 34249 30288]
 [36790 50113 53267]
 [19425 32591 29547]]
---------------
[[33580 28579 23123 26809 21521]
 [34703 26832 21772 24622 20563]
 [31051 29510 18104 22320 24751]
 [22260  9130 14256 13550  4752]
 [15667 16409  6362  8829 15475]]


array([[33580, 28579, 23123, 26809, 21521],
       [34703, 26832, 21772, 24622, 20563],
       [31051, 29510, 18104, 22320, 24751],
       [22260,  9130, 14256, 13550,  4752],
       [15667, 16409,  6362,  8829, 15475]])

# Power

In [52]:
print(arr)
print('-'*15)
print(arr**2)

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 21 45 40]]
---------------
[[ 625   16 3249 5329    1]
 [ 484  400 5625 1764  121]
 [ 484 1521  441 2025 1600]]


# 21. Percentile Function

In [67]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)

arr=np.sort(arr)
print(arr)
a=np.array([9,9,9,8])
print(np.percentile(a,9))
print(np.percentile(arr,9))



[9 4 9 9 1 6 4 6 8 7]
[1 4 4 6 6 7 8 9 9 9]
8.27
3.4299999999999997


# 22. Mean ,Variance and Standard devision

In [71]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)

print(arr.mean())
print(arr.var())
print(arr.std())


[9 4 9 9 1 6 4 6 8 7]
6.3
6.410000000000001
2.5317977802344327


# 23. Filtering an numpy arr

In [74]:
arr=np.arange(1,15)
print(arr)
print(arr>10)
print(arr[arr>10])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[False False False False False False False False False False  True  True
  True  True]
[11 12 13 14]


In [78]:
print(arr)
arr[arr>10]=5
print(arr)


[ 1  2  3  4  5  6  7  8  9 10  5  5  5  5]
[ 1  2  3  4  5  6  7  8  9 10  5  5  5  5]


# 24. Transposing array

In [80]:
arr=np.random.randint(1,10,(3,5))
print(arr,"\n","-"*15)
print(arr.T)

[[6 9 2 9 8]
 [9 2 1 6 5]
 [2 6 5 8 7]] 
 ---------------
[[6 9 2]
 [9 2 6]
 [2 1 5]
 [9 6 8]
 [8 5 7]]


# 25. where ()

In [88]:
arr=np.random.randint(1,10,10)
arr

array([2, 2, 6, 6, 8, 5, 4, 1, 1, 1])

In [89]:
arr1=np.where(arr%2==0,"even",arr)
arr1=np.where(arr%2!=0,"odd",arr1)
arr1

array(['even', 'even', 'even', 'even', 'even', 'odd', 'even', 'odd',
       'odd', 'odd'], dtype='<U11')

# 26. Merging arr

# concatenate

In [92]:
arr=np.random.randint(1,10,(2,4))
arr1=np.random.randint(1,10,(2,4))


print(arr)
print("-"*20)

print(arr1)

print("-"*20)
print(np.concatenate((arr,arr1),axis=0))
print("-"*20)

print(np.concatenate((arr,arr1),axis=1))




[[1 5 4 1]
 [9 3 8 3]]
--------------------
[[2 4 3 5]
 [2 3 3 8]]
--------------------
[[1 5 4 1]
 [9 3 8 3]
 [2 4 3 5]
 [2 3 3 8]]
--------------------
[[1 5 4 1 2 4 3 5]
 [9 3 8 3 2 3 3 8]]


# Vstack and Hstack

In [96]:
arr=np.random.randint(1,10,(2,4))
arr1=np.random.randint(1,10,(2,4))


print(arr)
print("-"*20)

print(arr1)
print("-"*20)

print(np.hstack((arr,arr1)))
print(np.vstack((arr,arr1)))

[[6 7 8 4]
 [6 2 9 3]]
--------------------
[[9 5 6 1]
 [9 8 2 3]]
--------------------
[[6 7 8 4 9 5 6 1]
 [6 2 9 3 9 8 2 3]]
[[6 7 8 4]
 [6 2 9 3]
 [9 5 6 1]
 [9 8 2 3]]


# 27. Splitting Array

In [100]:
arr1=np.random.randint(1,10,(4,4))
print(arr1)

np.vsplit(arr1,2)

[[7 4 7 8]
 [8 1 9 5]
 [6 5 6 1]
 [4 6 5 3]]


[array([[7, 4, 7, 8],
        [8, 1, 9, 5]]),
 array([[6, 5, 6, 1],
        [4, 6, 5, 3]])]

# 28. Turning Pics intp Numpy arrays

<img src="img.jpg">

In [102]:
from matplotlib.image import imread

In [103]:
img=imread("img.jpg")

In [104]:
img.shape

(4480, 6720, 3)

In [105]:
img

array([[[ 36,  74, 111],
        [ 36,  74, 111],
        [ 36,  74, 111],
        ...,
        [ 34,  30,  63],
        [ 34,  30,  63],
        [ 34,  30,  63]],

       [[ 36,  74, 111],
        [ 36,  74, 111],
        [ 36,  74, 111],
        ...,
        [ 34,  30,  63],
        [ 34,  30,  63],
        [ 34,  30,  63]],

       [[ 36,  74, 111],
        [ 36,  74, 111],
        [ 36,  74, 111],
        ...,
        [ 34,  30,  63],
        [ 34,  30,  63],
        [ 34,  30,  63]],

       ...,

       [[ 87,  84,  91],
        [ 77,  77,  85],
        [ 65,  72,  82],
        ...,
        [ 58, 105, 135],
        [ 62, 109, 139],
        [ 63, 110, 140]],

       [[ 76,  79,  88],
        [ 68,  75,  85],
        [ 57,  69,  81],
        ...,
        [ 58, 105, 135],
        [ 54, 101, 131],
        [ 54, 101, 131]],

       [[ 69,  76,  86],
        [ 66,  76,  86],
        [ 56,  72,  85],
        ...,
        [ 57, 104, 134],
        [ 54, 101, 131],
        [ 53, 100, 130]]

In [ ]:
f